blogcompany/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField
from wtforms.validators import DataRequired,Email,EqualTo

class BlogPostForm(FlaskForm):
    title=StringField('Title',validators=[DataRequired()])
    text=StringField('Text',validators=[DataRequired()])
    submit=SubmitField('Post')

blogcompany/blog_posts/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint,abort
from flask_login import current_user,login_required
from blogcompany import db
from blogcompany.models import BlogPost
from blogcompany.blog_posts.forms import BlogPostForm


blog_posts=Blueprint('blog_posts',__name__)

#create 
@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form=BlogPostForm()

    if form.validate_on_submit():
        blog_post=BlogPost(title=form.title.data,text=form.text.data,user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created')
        return redirect(url_for('core.index'))
    return render_template('create_post.html',form=form)


#view
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post=BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,date=blog_post.date,post=blog_post)
    

#update
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post=BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author!=current_user:
        abort(403)

    form=BlogPostForm()

    if form.validate_on_submit():
        blog_post.title=form.title.data
        blog_post.text=form.text.data
        db.session.commit()
        flash('Blog Post Updated')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))

    elif request.method=='GET':
        form.title.data=blog_post.title
        form.text.data=blog_post.text

    return render_template('create_post.html',title='Updating',form=form)

#delete
@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):
    blog_post=BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author!=current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')
    return redirect(url_for('core.index'))

blogcompany/core/views.py
#corr/views.py

from flask import render_template, request, Blueprint
from blogcompany.models import BlogPost
core=Blueprint('core',__name__)

@core.route('/')
def index():
    page=request.args.get('page',1,type=int)
    blog_posts=BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('index.html',blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

blogcompany/users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import current_user,login_required,logout_user,login_user
from blogcompany import db
from blogcompany.models import User,BlogPost
from blogcompany.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from blogcompany.users.picture_loader import add_profile_pic


users=Blueprint('users',__name__)

# register
@users.route('/register',methods=['GET','POST'])
def register():
    form=RegistrationForm()

    if form.validate_on_submit():
        user=User(email=form.email.data,
                  username=form.username.data,
                  password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering!')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)

#login 
@users.route('/login',methods=['GET','POST'])
def login():
    form=LoginForm()

    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Log in Success!')

            next=request.args.get('next')#if the user was trying to access a page that required login, this will redirect them to that page after login is successful 

            if next==None or not next[0]=='/':
                next=url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)

# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))

# account (update UserForm)
@users.route("/account",methods=['GET','POST'])
@login_required
def account():
    form=UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            username=current_user.username
            pic=add_profile_pic(form.picture.data,username)
            current_user.profile_image=pic

        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash('User Account Updated!')
        return redirect(url_for('users.account'))

    elif request.method=='GET':
        form.username.data=current_user.username
        form.email.data=current_user.email

    profile_image=url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)

# user's list of blog posts
@users.route("/<username>")
def user_posts(username):
    page=request.args.get('page',1,type=int)
    user=User.query.filter_by(username=username).first_or_404()
    blog_posts=BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

blogcompany/templates/account.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron text-center">
    <h1>Welcome to the Blog {{current_user.username}}</h1>
    <img class="rounded-circle" src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}" alt="Profile Image">
  </div>

  <div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
      {{form.hidden_tag()}}
      <div class="form-group">
        {{form.username.label(class='form-group')}}
        {{form.username(class='form-control')}}
      </div>
    
      <div class="form-group">
        {{form.email.label(class='form-group')}}
        {{form.email(class='form-control')}}
      </div>

      <div class="form-group">
        {{form.picture.label(class='form-group')}}
        {{form.picture(class='form-control-file')}}
      </div>

      <div class="form-group">
        {{form.submit(class='btn btn-primary')}}
      </div>
    </form>
  </div>
{% endblock %}

blogcompany/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <title>Blog Company</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{url_for('core.index')}}">Blog Company</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('core.index')}}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('core.info')}}">About</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.logout')}}">Log Out</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">Create Post</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container mt-4">
      {% block content %}
      {% endblock %}
    </div>
    <footer class="footer mt-auto py-3 bg-light">
      <div class="container">
        <span class="text-muted">&copy; 2025 Blog Company</span>
      </div>
    </footer>
  </body>
</html>

blogcompany/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>{{post.title}}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{post.date.strftime('%B %d, %Y')}}</h3>
  <p>{{post.text}}</p>

  {% if post.author == current_user %}
  <div>
    <a class="btn btn-warning" href="{{url_for('blog_posts.update',blog_post_id=post.id)}}">Update</a>
    <button type="button" class="btn btn-danger" data-toggle='modal' data-target="#del_modal">Delete</button>
  </div>
  {% endif %}
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="post">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blogcompany/templates/create_post.html
{% extends "base.html" %}
{% block content %}
  <div class="container mt-4">
    <h1>Create a New Post</h1>
    <form method="POST" enctype="multipart/form-data">
      {{form.hidden_tag()}}
      <div class="form-group">
        {{form.title.label(class="form-control-label")}}
        {{form.title(class="form-control form-control-lg")}}
      </div>
      <div class="form-group">
        {{form.text.label(class="form-control-label")}}
        {{form.text(class="form-control form-control-lg")}}
      </div>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info")}}
      </div>
    </form>
  </div>
{% endblock %}

blogcompany/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron text-center">
    <h1>Blogs</h1>
  </div>

  <div class="container">
    {% for post in blog_posts.items %}
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title"><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
          <p class="card-text">Written by <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a></p>
          <p class="card-text">Published on {{post.date.strftime('%Y-%m-%d')}}</p>
          <a class="btn btn-primary" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">Read More</a>
        </div>
      </div>
    {% endfor %}
  </div>

  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class="page-item active">
          <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{ page_num }}</a>
        </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>
{% endblock %}

blogcompany/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron text-center">
    <h1>Info about our company</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
{% endblock %}

blogcompany/templates/login.html
{% extends "base.html" %}
{% block content %}
  <div class="container mt-4">
    <h1>Login</h1>
    <form method="POST">
      {{form.hidden_tag()}}
      <div class="form-group">
        {{form.email.label(class="form-control-label")}}
        {{form.email(class="form-control")}}
      </div>
      <div class="form-group">
        {{form.password.label(class="form-control-label")}}
        {{form.password(class="form-control")}}
      </div>
      <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
      </div>
    </form>
  </div>
{% endblock %}

blogcompany/templates/register.html
{% extends "base.html" %}
{% block content %}
  <div class="container mt-4">
    <h1>Register</h1>
    <form method="POST">
      {{form.hidden_tag()}}
      <div class="form-group">
        {{form.email.label(class="form-control-label")}}
        {{form.email(class="form-control")}}
      </div>
      <div class="form-group">
        {{form.username.label(class="form-control-label")}}
        {{form.username(class="form-control")}}
      </div>
      <div class="form-group">
        {{form.password.label(class="form-control-label")}}
        {{form.password(class="form-control")}}
      </div>
      <div class="form-group">
        {{form.pass_confirm.label(class="form-control-label")}}
        {{form.pass_confirm(class="form-control")}}
      </div>
      <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
      </div>
    </form>
  </div>
{% endblock %}

blogcompany/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron text-center">
    <h1>Welcome to the page for {{user.username}}</h1>
    <img class="rounded-circle" src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}" alt="Profile Image">
  </div>

  {% for post in blog_posts.items %}
    <div class="card mb-4">
      <div class="card-body">
        <h2 class="card-title"><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
        <p class="card-text">Written by <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a></p>
        <p class="card-text text-muted">Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
        <p class="card-text">{{post.text}}</p>
      </div>
    </div>
  {% endfor %}
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if blog_posts.page == page_num %}
      <li class="page-item active">
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num }}</a>
      </li>
      {% else %}
      <li class="page-item">
        <a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{ page_num }}</a>
      </li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endblock %}